security:

    encoders:
        Symfony\Component\Security\Core\User\User: bcrypt
        App\Entity\User: 'auto'

        #php bin/console security:encode-password

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        #in_memory:
        #    memory:
        #        users:
        #            beam:
        #                password:
        #                roles: 'ROLE_USER'

        #            admin:
        #                password:
        #                roles: 'ROLE_ADMIN'



        user_provider:
            entity:
                class: App\Entity\User
                property: username


    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            anonymous: true

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

            form_login:
                login_path: login
                check_path: connexion_check
                default_target_path: check_statut

                # a voir pour les redirections après connexion

            logout:
                path: logout
                target: index


    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/login, allow_if: "not is_granted('ROLE_USER')" }
        - { path: ^/register, allow_if: "not is_granted('ROLE_USER')" }




    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
