swiftmailer:
    transport:        gmail
    username:         evogue.dev@gmail.com # adresse à laquelle on envoie les mails en prod
    password:         Formation2019
    host:             localhost
    port:             465
    encryption:       ssl
    auth-mode:        login
    spool: { type: 'memory' }
    stream_options:
        ssl:
            allow_self_signed: true
            verify_peer: false
            verify_peer_name: false