# See https://symfony.com/doc/current/email/dev_environment.html
swiftmailer:
    # send all emails to a specific address
    delivery_addresses: ['bldlr170289@gmail.com'] 
    # ^ adresse de Bart pour le test dev
